use_frameworks!

platform :ios, '8.0'

target 'YDCTMediatorSDK_Example' do
  pod 'YDCTMediatorSDK', :path => '../'

  target 'YDCTMediatorSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
